### ISSUE TITLE
can't obtain array of values

### ISSUE THREAD

**Issue by mluis** [twolfson/reverse-mustache#7]
Given a template of
```
{{#places}}{{name}}{{/places}}
```
I'm obtaining an object. Can't obtain an array of places. Would this be possible?

**Comment by twolfson** [comment]
I don't think so. The `mustache` language oversimplifies types a bunch -- this is an example of such a collision. We'd be better off with a language like `handlebars`. I started exploring that here but abandoned it at a similar time:

https://github.com/twolfson/reverse-template
