### ISSUE TITLE
If else conditional statement in reverse-mustache

### ISSUE THREAD

**Issue by peeyushjss** [twolfson/reverse-mustache#8]
Hi, I have a issue while  using if else in reverse -mustache

Foreg: 

{{#success}}0{{/success}}{{#!success}}1{{/success}}

If(true)
console.log("-------");
else
console.log("****************");

Under above eg i want another case for 3 as well.

Please suggest.

**Comment by twolfson** [comment]
It sounds like `{{success}}` is supposed to be a variable (e.g. 0/1/3) so this isn't an if/else but:

```
{{success}}
```
